spring.application.name=LokalDeals

# Database Configuration (MySQL 8.0)
spring.datasource.url=jdbc:mysql://localhost:3306/LokalDeals?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=your_mysql_password

# Hibernate JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Custom Application Token Settings
jwt.secret=9a72cede95c94e09e13a6d713c42878bf8f47b255e2d6b3a0050875e6a9821a8
jwt.expiration=86400000

spring.datasource.url=jdbc:mysql://localhost:3306/LokalDeals?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root